name: DVWA SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud-dvwa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, curl

    - name: Run SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=dvwa
          -Dsonar.organization=faizaladdp
          -Dsonar.sources=.
          -Dsonar.exclusions=config/**,docs/**,tests/**

    - name: Clean Sonar scanner cache
      run: rm -rf $HOME/.sonar/cache