name: OWASP ZAP Automation Scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Automation Framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify ZAP config
        run: |
          if [ ! -f "zap-config/autorun.yaml" ]; then
            echo "❌ zap-config/autorun.yaml not found!"
            exit 1
          fi

      - name: Run ZAP Automation Framework
        uses: MisterIcy/zap-automation-framework@main
        with:
          config-dir: 'zap-config'
          autorun-file: 'autorun.yaml'
          docker-image: 'owasp/zap2docker-stable:latest'
          create-annotations: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-config/
